version: 2

sources:
  - name: fam_fp
    schema: dvh_fam_fp
    tables:
      - name: fam_fp_meta_data
        description: 'inneholder meta_data for FP'
      - name: json_fam_fp_fagsak
        description: 'inneholder fagsak info for FP'

  - name: person
    schema: dt_person
    tables:
      - name: ident_aktor_til_fk_person1_ikke_skjermet



